production:
  adapter: sqlite3
  # database: ':memory:'
  database: fitl
  pool: 5,
  timeout: 5000

development:
  adapter: sqlite3
  # database: ':memory:'
  database: fitl_development.db
  pool: 5,
  timeout: 5000

test:
  adapter: sqlite3
  # database: ':memory:'
  database: fitl_test.db
  pool: 5,
  timeout: 5000
